### ISSUE TITLE
cavalas cavalonas

### ISSUE THREAD

**Issue by Kisrym** [Bebel132/Lista-de-Compras#1]
meu Deus por favor, nunca te pedi por nada perto de uma beldade dessas, só 1, preciso de só 1

**Comment by Bebel132** [comment]
Pedro Paulo Pereira Pinto, pequeno pintor português, pintava portas, paredes, portais. Porém, pediu para parar porque preferiu pintar panfletos. Partindo para Piracicaba, pintou prateleiras para poder progredir. Posteriormente, partiu para Pirapora. Pernoitando, prosseguiu para Paranavaí, pois pretendia praticar pinturas para pessoas pobres. Porém, pouco praticou, porque Padre Paulo pediu para pintar panelas, porém posteriormente pintou pratos para poder pagar promessas. . Pálido, porém perseverante, preferiu partir para Portugal para pedir permissão para papai para permanecer praticando pinturas, preferindo, portanto, Paris. Partindo para Paris, passou pelos Pirineus, pois pretendia pintá-los. Pareciam plácidos, porém, pesaroso, percebeu penhascos pedregosos, preferindo pintá-los parcialmente, pois perigosas pedras pareciam precipitar-se principalmente pelo Pico, porque pastores passavam pelas picadas para pedirem pousada, provocando provavelmente pequenas perfurações, pois, pelo passo percorriam, permanentemente, possantes potrancas. Pisando Paris, pediu permissão para pintar palácios pomposos, procurando pontos pitorescos, pois, para pintar pobreza, precisaria percorrer pontos perigosos, pestilentos, perniciosos, preferindo Pedro Paulo precaver-se. Profundas privações passou Pedro Paulo. Pensava poder prosseguir pintando, porém, pretas previsões passavam pelo pensamento, provocando profundos pesares, principalmente por pretender partir prontamente para Portugal. Povo previdente! Pensava Pedro Paulo… "Preciso partir para Portugal porque pedem para prestigiar patrícios, pintando principais portos portugueses". . Passando pela principal praça parisiense, partindo para Portugal, pediu para pintar pequenos pássaros pretos. Pintou, prostrou perante políticos, populares, pobres, pedintes. - "Paris! Paris!" Proferiu Pedro Paulo. -"Parto, porém penso pintá-la permanentemente, pois pretendo progredir". Pisando Portugal, Pedro Paulo procurou pelos pais, porém, Papai Procópio partira para Província. Pedindo provisões, partiu prontamente, pois precisava pedir permissão para Papai Procópio para prosseguir praticando pinturas. Profundamente pálido, perfez percurso percorrido pelo pai. Pedindo permissão, penetrou pelo portão principal. Porém, Papai Procópio puxando-o pelo pescoço proferiu: -Pediste permissão para praticar pintura, porém, praticando, pintas pior. Primo Pinduca pintou perfeitamente prima Petúnia. Porque pintas porcarias? -Papai, proferiu Pedro Paulo, pinto porque permitiste, porém preferindo, poderei procurar profissão própria para poder provar perseverança, pois pretendo permanecer por Portugal. Pegando Pedro Paulo pelo pulso, penetrou pelo patamar, procurando pelos pertences, partiu prontamente, pois pretendia pôr Pedro Paulo para praticar profissão perfeita: pedreiro! Passando pela ponte precisaram pescar para poderem prosseguir peregrinando. Primeiro, pegaram peixes pequenos, porém, passando pouco prazo, pegaram pacus, piaparas, pirarucus. Partindo pela picada próxima, pois pretendiam pernoitar pertinho, para procurar primo Péricles primeiro.
